### ISSUE TITLE
text_to_speech Beta service fail

### ISSUE THREAD

**Issue by ThreeGe** [watson-developer-cloud/ios-sdk#145]
Hi，

I follow your quick start guide,  and change 
static let serviceURL = "https://stream.watsonplatform.net/text-to-speech/api"
to
static let serviceURL = "https://stream.watsonplatform.net/text-to-speech-beta/api"
,since I used a beta service to bind to my app. After run this project, i got error message:
Optional(Error Domain=com.ibm.mil Code=403 "(null)" UserInfo={localizedDescription=Response code was unacceptable: 403})

**Comment by glennrfisher** [comment]
Hi @ThreeGe,

Would you mind following the documentation on [Obtaining Credentials for Watson Services](https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/getting_started/gs-credentials.shtml) in order to verify the url for your text-to-speech service?

In particular, is the url shown in your BlueMix console
`https://stream.watsonplatform.net/text-to-speech/api` or
`https://stream.watsonplatform.net/text-to-speech-beta/api`?

I ask because I am not familiar with the text-to-speech-beta service that you mentioned.

Unfortunately, if you are using a text-to-speech-beta service we may not be able to support it with the iOS SDK—we do not currently have access to a text-to-speech-beta service that we can use for testing and debugging.

I wonder if you are using an earlier version of the service. Perhaps you can instantiate and bind a new text-to-speech service instead of modifying the iOS SDK source code?

Let us know what you find! We'd love to help get you up-and-running with the iOS SDK. Please feel free to share any and all feedback about your experiences with the SDK, too.

Best,
Glenn

**Comment by ThreeGe** [comment]
Hi @glennrfisher ,
Thanks for your reply!

I have tried your advice, SDK worked with the text-to-speech service, not with the `beta` one.
From bluemix, I create an app and add some services that are beta version for my first trial, then I met this  fail. 
It's clear for me now.

Best Regards,
Riven

**Comment by glennrfisher** [comment]
Glad you got it working, @ThreeGe! :)
