### ISSUE TITLE
Xcode 7.3 and iOS 9.3 causes an error when importing Watson cloud (see screenshot)

### ISSUE THREAD

**Issue by sujithv28** [watson-developer-cloud/ios-sdk#212]
I just updated my Xcode to 7.3 and now the build no longer succeeds. I see this error message:

<img width="1419" alt="screen shot 2016-03-24 at 12 41 59 pm" src="https://cloud.githubusercontent.com/assets/5770052/14024071/f85a034a-f1bd-11e5-90a0-6cafb503828d.png">

**Comment by glennrfisher** [comment]
The particular problem you're seeing is because the `WatsonDeveloperCloud` framework (and its dependencies) were built by Carthage using Xcode 7.2. To rebuild the framework using Xcode 7.3, navigate to your project directory and run `carthage update --platform iOS` again.

However, we are experiencing [other problems](https://github.com/watson-developer-cloud/ios-sdk/issues/210) with Xcode 7.3 that will prevent you from being able to use Xcode 7.3 to build the `WatsonDeveloperCloud` framework. Unfortunately, while we're working to resolve this issue, you will need to use Xcode 7.2 to develop with the `WatsonDeveloperCloud`. Here are [instructions](https://github.com/watson-developer-cloud/ios-sdk/issues/210#issuecomment-200977378) for doing so.
