### ISSUE TITLE
XCode7.3 Error: Module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by juanpdelat** [watson-developer-cloud/ios-sdk#214]
After updating XCode to 7.3, **needed if you want to debug apps on devices that have iOS 9.3**, I cannot build my application anymore, I am getting an error "Module file was created by an older version of the compiler; reuild 'WatsonDeveloperCloud' and try again: /Users/....../WatsonDeveloperCloud.swiftmodule/x86_64.swiftmodule.

**Comment by glennrfisher** [comment]
Please see #212. We are still working to add support for Xcode 7.3.

**Comment by juanpdelat** [comment]
Thanks for the super fast response but I consider this bug should be still open, I'm not being rude or anything, but closing the tickets and asking developers to use older versions, is not the best response IMHO, especially when devices running the latest iOS version are unusable.

**Comment by glennrfisher** [comment]
Hi @juanpdelat. That's a good suggestion, but this particular bug is related to the way consumers build the SDK, not any of the SDK code itself.

In other words, the `Module file was created by an older version of the compiler` error that you receive is because you haven't built the SDK using Xcode 7.3. This error will be resolved when you re-run Carthage to build the SDK with Xcode 7.3.

Of course, you _can't_ build the SDK because it is not yet supported in Xcode 7.3. That _is_ because of code within our SDK that fails to compile because of changes made to Xcode. We're tracking that bug with issue #210, which will remain open until we have a resolution.

Always happy to hear suggestions about how to manage the repository, though! We're always learning and open to improvements. So we appreciate your feedback!
