### ISSUE TITLE
Move examples to a new repository

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#288]
All developers using the iOS SDK currently have to download the "Examples" directory when building the SDK with Carthage.

Let's move the Speech to Text example to a new repository. We'll also need to update the readme to link to the new repository.

**Comment by glennrfisher** [comment]
There are a few examples that need to be moved:

- [ ] [Speech to Text example application](https://github.com/watson-developer-cloud/ios-sdk/tree/master/Examples/SpeechToText)
- [ ] [Chat application](https://github.com/IBM-MIL/ios-sdk-chat-app)
- [ ] [WatsonSpeaks application](https://github.com/IBM-MIL/ios-sdk-watson-speaks)

**Comment by germanattanasio** [comment]
There are some advantages of having the examples with the code. In fact, we have an `examples` folder in all the SDKs.  Having the examples in a different project will affect the maintainability since now we need to keep 2 repositories updated and whenever a user submit a PR we need to ask him to update the code in another repo also.

Can we tell Carthage to ignore the `examples` folder ? 
How big (in MB) is the folder?

**Comment by glennrfisher** [comment]
I agree that we should have some examples in the SDK. But I don't think we should have full iOS applications. The Speech to Text example is not large, but others will be.

**Comment by germanattanasio** [comment]
Makes sense

**Comment by glennrfisher** [comment]
Complete with da2ef0f835434444cc8682f420969efd18dec97c.
