### ISSUE TITLE
[text-to-speech] Japanese text must be percent encoded before passed to synthesize method

### ISSUE THREAD

**Issue by clindsay** [watson-developer-cloud/ios-sdk#421]
When I use the synthesize method with Japanese text, I get an error. However, if I percent encode the text before passing it to the TTS API, it works properly. 

It seems like the percent encoding should be handled internally.

Steps to reproduce:
```
let tts = TextToSpeech(username: "...", password: "...")
let failure = { (error: NSError) in print(error) }
tts.synthesize("こんにちは", voice: SynthesisVoice.JP_Emi, customizationID: nil, audioFormat: .WAV, failure: failure) { ... }
```

Expected behavior:
The voice should speak the word "konnichiwa"

Actual behavior:
The failure callback is invoked, and this error is printed:
`Error Domain=com.ibm.watson.developer-cloud.TextToSpeechV1 Code=0 "Returned audio is in an unexpected format." UserInfo={NSLocalizedFailureReason=Returned audio is in an unexpected format.}`

If I manually percent encode the string, it works:
```
let tts = TextToSpeech(username: "...", password: "...")
let failure = { (error: NSError) in print(error) }
tts.synthesize("こんにちは".stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet())!, voice: SynthesisVoice.JP_Emi, customizationID: nil, audioFormat: .WAV, failure: failure) { ... }
```

**Comment by glennrfisher** [comment]
Good catch! We'll push a bug fix soon and be sure to add a test with Japanese.

**Comment by clindsay** [comment]
Great! =)

**Comment by glennrfisher** [comment]
I was able to add a test for Japanese text with no problem--I did not need to add any additional percent encoding. Browsing through the code, though, I think you received an improperly formatted error response from Watson, which the SDK tried to parse as WAV data.

For example, if your credentials were invalid, then you would receive an HTML page like that described in #423. Since that HTML page isn't parsed as a JSON error, it is instead parsed as WAV data. Of course, that's not a proper WAV file, resulting in the "Returned audio is in an unexpected format" error message.

So I'm going to close this issue in favor of #423 and #375, which should introduce better error handling to the SDK and avoid the cryptic "Returned audio is in an unexpected format" message.
