### ISSUE TITLE
Add support for Swift 2.3

### ISSUE THREAD

**Issue by slizeray** [watson-developer-cloud/ios-sdk#428]
I am a bit of surprised that there is no Swift 2.3 and Swift 3.0 branches.

iOS10 is about to be released along with XCode 8.

When the Watson SDK will be available in Swift 3.0 ?

Thanks,

Stéphane

**Comment by glennrfisher** [comment]
Hi @slizeray. We're planning to support Swift 3.0 very soon after its release (we've been kicking around #376 for awhile). We have a few important issues that we need to tackle first, but will then be spending some time migrating the SDK to support Swift 3.0.

One of the reasons we've been holding off is because of a change we are planning to the project's structure (#369). We've been burned by merge conflicts with project files before, so we would like to re-organize the project before creating a Swift 3.0 branch.

**Comment by slizeray** [comment]
OK, what about Swift 2.3 ? My concern is that I must do a classroom on the 24th of september. By that time, all participants will bring their laptop with XCode 8.
Swift 3 is major break change and the migration is very painful. I am not sure that the Watson SDK 3 will be ready. Would it be possible to have a Swift 2.3 branch in between? Thanks.

**Comment by glennrfisher** [comment]
Okay, we'll do our best to add support for Swift 2.3 as soon as we can.

**Comment by teddynewell** [comment]
Looks like the Freddy dependency from https://github.com/bignerdranch/Freddy would need to be set to the master branch or a specific commit.  They haven't added any versioned releases in awhile.

**Comment by glennrfisher** [comment]
I opened a PR (#441) yesterday to add Swift 2.3 support. We expect to merge it and publish a release soon.

Yeah. We might want to ask them to do a versioned release. I set a specific commit for now (that way new commits won't be a surprise--for example, if they push Swift 3.0 support to the master branch).

Long time, no see @teddynewell! :)

**Comment by glennrfisher** [comment]
We just published v0.8.0 with Swift 2.3 support.

**Comment by teddynewell** [comment]
Super!
