### ISSUE TITLE
Carthage Update issue: Parse error

### ISSUE THREAD

**Issue by spjoynt** [watson-developer-cloud/ios-sdk#442]
Having a problem when issuing the command `$ carthage update --platform iOS` 

I get the following error. 

 `*** Fetching ios-sdk
*** Fetching Starscream
*** Fetching Freddy
*** Fetching Alamofire
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD Carthage/Checkouts/Alamofire) but encountered:`

Xcode 8 - Swift 3 - iOS 10 build

**Comment by glennrfisher** [comment]
Hmm... that's a very strange error, because I don't think Alamofire has any Git submodules.

Can you try this again? Maybe in a fresh directory?

One thing to note is that we don't yet support Swift 3.0. We recently updated to Swift 2.3 with the v0.8.0 release and will be updating to Swift 3.0 in a few weeks.

**Comment by spjoynt** [comment]
Thanks...I'm not sure why I would get this error in the current directory and not another. I checked folder permissions with nothing looking out of place. 

I look forward to the Swift 3.0 release.

**Comment by glennrfisher** [comment]
Glad it's working! That is definitely very strange indeed...

Thanks for mentioning Swift 3.0. It helps us get a gauge for how many users
want to use Swift 3.0. That in turn helps us prioritize the work in our
backlog.
