### ISSUE TITLE
Investigate inconsistencies between users

### ISSUE THREAD

**Issue by troyibm** [watson-developer-cloud/ios-sdk#460]
I'm pretty much using the example for SpeechToTextSession in the readme.
I can get text returned to STTS.onResult(), but two of my co-workers (the only other two that have tried it) cannot.  I wish there was example they could try that has been proven to work.

We have both Siri STT and Watson STT in this app.  I originally had removed the Siri STT portion when I was running the app (I didn't have my hands on a provisioning profile with SiriKit entitlement) and both co-workers did.  But I since got ahold of a prov profile so using the same code they are on same devices.  I'm not sure they are running on the same iOS level (i'm sure it is ios10, but it might not be 10.0.2 but shouldn't matter).

Maybe there is some debugging I can turn on or build the 0.8.0 source and see what is going on?  Maybe do a screenhero screen share?

I can't reproduce the problem myself.  Looking for things they could try and I'll update this issue with more info when I get it.

One screen shot shows a portion of an error message from Watson SDK.  It says "...out, no data received in the last 30 seconds".  For the other co-worker, there wasn't an error from Watson SDK, but we did see this error: "Error Domain=kCLErrorDomain Code=0 "(null)"" which google shows this more of a CLLocation type of error.

**Comment by troyibm** [comment]
More info on this problem. Seems it is intermittent. 

Scenario 1 : When we get one of the following errors, any requests made fails. Also, I have observed that these errors randomly occur but once we get one of these errors , we continue to get this error repeatedly for requests which follow.

watsonSTT.onError: Error Domain=NSPOSIXErrorDomain Code=54 "Connection reset by peer" UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=54}
watsonSTT.onError: Error Domain=com.ibm.watson.developer-cloud.SpeechToTextV1 Code=0 "Expected a JSON header message before receiving binary data." UserInfo={NSLocalizedFailureReason=Expected a JSON header message before receiving binary data.}

**Comment by glennrfisher** [comment]
Hey @troyibm. Are you and your co-workers still experiencing this problem?

I'm a little confused--is everyone running the same app (checked into source control somewhere) or are you testing with different applications?

If running the same app, then I can't think why it would work for one person and not another. But if that's the case, we can try to investigate further.

If running different applications (even with the same Speech to Text code copy/pasted), then I wonder if it could be a problem with the app transport security settings? See step 9 of the [quickstart guide](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Documentation/Quickstart.md) for information on configuring the app transport security settings.

We took a look at the `expected a JSON header message before receiving binary data` error on Friday. We found a bug in the SDK the prevented queued operations from pausing when the _server_ causes the session to disconnect instead of the client. We fixed that in the `swift-2.2` branch and will be merging the fix into the `master` and `swift-3.0` branches soon.

**Comment by glennrfisher** [comment]
Do you know if your co-workers have defined a `failure` function to capture error messages? If so, do they see any error messages with their application?

**Comment by troyibm** [comment]
> I'm a little confused--is everyone running the same app (checked into source control somewhere) or are you testing with different applications?

Same app.

> Do you know if your co-workers have defined a failure function to capture error messages? If so, do they see any error messages with their application?

Yes, we do have a failure function.  I'll try to get you the info.  We've since moved to using different approach that seems to be working fine.  We aren't using SpeechToTextSession anymore since two of the team members were getting errors.

**Comment by glennrfisher** [comment]
Glad you found something that works for you! Are you still using the SDK or did you decide to use the speech recognition functionality in iOS 10?

**Comment by troyibm** [comment]
Been told to use Watson STT as we are working on World of Watson demo.  But I've been asked to put in a switch for Siri.  From limited testing in the last couple of days, Watson STT is misinterpreting words more than Siri is.

**Comment by glennrfisher** [comment]
Hey, @troyibm! Are you still experiencing this issue? I'm going to close it for now, but let us know if it's still a problem and we can reopen it.
