### ISSUE TITLE
RecognitionSettings contentType issue

### ISSUE THREAD

**Issue by impiyush** [watson-developer-cloud/ios-sdk#524]
Using any specified AudioMediaType formats in the contentType of RecognitionSettings is not being recognized. I'm using `RecognitionSettings(contentType: .wav)` which gives an error that wav is not recognized as a valid AudioMediaType. Also tried with .flac and .opus, same error.

Also checked the [Struct Reference](http://watson-developer-cloud.github.io/ios-sdk/services/SpeechToTextV1/Structs/RecognitionSettings.html) which leads to broken links.

**Comment by glennrfisher** [comment]
Hi @impiyush. It's possible that you caught us in between versions. If you cloned the SDK yesterday, you might have downloaded v0.8.0. We recently released v0.9.0 with Swift 3.0 support, though, and updated the documentation accordingly. With Swift 3.0, the convention has changed to start enums with a lower case instead of an upper-case, so `.WAV` became `.wav`.

So if you're using v0.8.0, try capitalizing the enum case: `RecognitionSettings(contentType: .WAV)`. If that doesn't work, let us know and we'll look into it further.

Thanks for letting us know about the broken links. Those pages moved on the IBM site recently. We fixed them in our readme, but must have missed them in the comments of the SDK (which is used to generate the documentation). We'll be sure to update that!

**Comment by glennrfisher** [comment]
I'm going to close this issue because I think using `.WAV` instead of `.wav` will work. (Or upgrading to v0.9.0 with Swift 3.0 support and using `.wav`.)

Please let us know if it doesn't, though--we're happy to reopen the issue and continue looking into it.

FYI: Broken links are fixed with #525
